// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2X8oECOAL-kUg_tmrhhFXDCX4fhJKNho',
    appId: '1:751869552061:web:71f8dad137322bffb3ded4',
    messagingSenderId: '751869552061',
    projectId: 'my-chat-app-cc79f',
    authDomain: 'my-chat-app-cc79f.firebaseapp.com',
    storageBucket: 'my-chat-app-cc79f.appspot.com',
    measurementId: 'G-N8J86MY8CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeKiCiYoZFpUWRj0lHs5PIlH5H_KnKjCE',
    appId: '1:751869552061:android:cdc1ed7d97ce06b3b3ded4',
    messagingSenderId: '751869552061',
    projectId: 'my-chat-app-cc79f',
    storageBucket: 'my-chat-app-cc79f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4VXuZvEXHhzQIBSepXraZmSovEl3Aub4',
    appId: '1:751869552061:ios:59dfce77cb051532b3ded4',
    messagingSenderId: '751869552061',
    projectId: 'my-chat-app-cc79f',
    storageBucket: 'my-chat-app-cc79f.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4VXuZvEXHhzQIBSepXraZmSovEl3Aub4',
    appId: '1:751869552061:ios:59dfce77cb051532b3ded4',
    messagingSenderId: '751869552061',
    projectId: 'my-chat-app-cc79f',
    storageBucket: 'my-chat-app-cc79f.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2X8oECOAL-kUg_tmrhhFXDCX4fhJKNho',
    appId: '1:751869552061:web:d030468d6d73fa9fb3ded4',
    messagingSenderId: '751869552061',
    projectId: 'my-chat-app-cc79f',
    authDomain: 'my-chat-app-cc79f.firebaseapp.com',
    storageBucket: 'my-chat-app-cc79f.appspot.com',
    measurementId: 'G-3D8R97RKV3',
  );
}
